export const countries = [{ label: "Ethiopia" }];

export const subCities = ["Yeka", "Arada", "Lafto"];

export const cities = [
  { label: "Adama" },
  { label: "Addis Ababa" },
  { label: "Adigrat" },
  { label: "Adwa" },
  { label: "Agaro" },
  { label: "Alaba Kulito" },
  { label: "Alamata" },
  { label: "Alemaya" },
  { label: "Aleta Wendo" },
  { label: "Ambo" },
  { label: "Arba Minch" },
  { label: "Areka" },
  { label: "Arsi Negele" },
  { label: "Asella" },
  { label: "Asosa" },
  { label: "Axum" },
  { label: "Bahir Dar" },
  { label: "Bale Robe" },
  { label: "Bishoftu" },
  { label: "Boditi" },
  { label: "Bonga" },
  { label: "Bule Hora Town" },
  { label: "Burayu" },
  { label: "Butajira" },
  { label: "Chagni" },
  { label: "Chiro" },
  { label: "Dangila" },
  { label: "Debere wereke" },
  { label: "Debre Birhan" },
  { label: "Debre Markos" },
  { label: "Debre Tabor" },
  { label: "Degehabur" },
  { label: "Dembi Dolo" },
  { label: "Dessie" },
  { label: "Dilla" },
  { label: "Dejene" },
  { label: "Dire Dawa" },
  { label: "Durame" },
  { label: "Fiche" },
  { label: "Finote Selam" },
  { label: "Gambela" },
  { label: "Gimbi" },
  { label: "Goba" },
  { label: "Gode" },
  { label: "Gondar" },
  { label: "Harar" },
  { label: "Hawassa" },
  { label: "Hosaena" },
  { label: "Jijiga" },
  { label: "Jimma" },
  { label: "Jinka" },
  { label: "Kobo" },
  { label: "Kombolcha" },
  { label: "Mekelle" },
  { label: "Meki" },
  { label: "Metu" },
  { label: "Mizan Teferi" },
  { label: "Modjo" },
  { label: "Mota" },
  { label: "Negele Borana" },
  { label: "Nekemte" },
  { label: "Sawla" },
  { label: "Sebeta" },
  { label: "Shashamane" },
  { label: "Shire Inda Selassie" },
  { label: "Sodo" },
  { label: "Tepi" },
  { label: "Welkite" },
  { label: "Wolaita Dimtu" },
  { label: "Woldiya" },
  { label: "Woliso" },
  { label: "Wukro" },
  { label: "Yirgalem" },
  { label: "Ziway" },
];
